#!/usr/bin/python
#-*-coding:utf-8-*-

import sys
import rospy
from PySide.QtGui import *
from PySide.QtCore import *
from PySide import QtGui, QtCore
from views import NavControlUI

def on_shutdown():
    print '--- On Shutdown ---'

def main():
    print 'nav_manager v 1.0.0'

    try:
        qt_app = QApplication(sys.argv)

        rospy.init_node('nav_manager')
        ui = NavControlUI()
        rospy.on_shutdown(on_shutdown)
        qt_app.exec_()

    except rospy.ROSInterruptException:
        pass

if __name__ == '__main__':
    main()

